server:
  port: 8081

spring:
  application:
    name: ms-winepurchase
  jackson:
    serialization:
      indent_output: true
    default-property-inclusion: non_null

cors:
  allowed-origins: "*"
  allowed-methods: "*"

springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs